- name: Install Nginx server and update the cache
  apt:
    name: nginx
    state: latest
    update_cache: yes
  become: yes

- name: Check Nginx is started and enabled to start at boot time.
  service:
      name: nginx
      state: started
      enabled: yes

- name: Create target directory
  file:
    path: /var/www/static_web_app
    state: directory
    mode: 0755

- name: copy the content of the web site
  copy:
    src: index.html
    dest: /var/www/static_web_app/index.html


- name: copy the ssl certificate and private key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
    owner: root
    group: root
  with_items:
    - { src: nginx.crt, dest: /etc/ssl/certs/localhost.crt }
    - { src: nginx.key, dest: /etc/ssl/private/localhost.key }

- name: copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/nginx.conf

- name: create symlink
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/default
    state: link


- name: Restart Ngnix number
  service:
    name: nginx
    state: restarted
